In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [7]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(array2.shape)

(15,)


In [8]:
matrix = array2.reshape(5, 3)
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [9]:
print(matrix.shape)

(5, 3)


In [10]:
print(matrix.ndim)

2


In [11]:
print(matrix.dtype.name)

int32


In [12]:
print(matrix.size)

15


In [13]:
print(type(matrix))

<class 'numpy.ndarray'>


In [18]:
matrix2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matrix2)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
print(matrix2.shape)

(2, 4)


In [23]:
zeros = np.zeros((4, 4))

In [24]:
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
zeros[1, 1] = 22
print(zeros)

[[ 0.  0.  0.  0.]
 [ 0. 22.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [26]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [41]:
list = [1, 2, 3, 4, "yes comas"]
array6 = np.array(["I", "am", "array", "(no comas)"])
print(list)
print(array6)

[1, 2, 3, 4, 'yes comas']
['I' 'am' 'array' '(no comas)']


In [42]:
array = np.array([1, 2, 3])
p1 = array
p2 = array

In [47]:
p1[0] = 1111
p2[1] = 2222
print(array)

[1111 2222    3]


In [52]:
copyArray = array.copy()
print(copyArray)

[1111 2222    3]


In [53]:
print(array[0:2]) #inclusive, exclusive

[1111 2222]


In [54]:
print(matrix)
print(matrix[0, 0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
1


In [55]:
print(matrix[1, 0:2])

[4 5]


In [56]:
print(matrix[:, -1])

[ 3  6  9 12 15]


In [57]:
print(matrix[0, -1])

3


In [58]:
array = matrix.ravel()
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [65]:
matrix.T

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [72]:
#resize method does NOT do changes to its array, you have to assign.
print(matrix)
np.resize(matrix, (5, 3))
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
